# Generated by Django 3.2.13 on 2022-06-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelCrud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColdDrinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flavour', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
