# Generated by Django 3.2.13 on 2022-06-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelCrud', '0002_colddrinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
